/* Generated by Yosys 0.9+3621 (git sha1 84e9fa7, gcc 8.3.1 -fPIC -Os) */

module pes_bc(Clk, reset, UpOrDown, Count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  input Clk;
  output [3:0] Count;
  input UpOrDown;
  input reset;
  sky130_fd_sc_hd__inv_2 _23_ (
    .A(reset),
    .Y(_14_)
  );
  sky130_fd_sc_hd__buf_1 _24_ (
    .A(_14_),
    .X(_13_)
  );
  sky130_fd_sc_hd__buf_1 _25_ (
    .A(_14_),
    .X(_12_)
  );
  sky130_fd_sc_hd__inv_2 _26_ (
    .A(Count[0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__buf_1 _27_ (
    .A(_04_),
    .X(_05_)
  );
  sky130_fd_sc_hd__or2_2 _28_ (
    .A(Count[0]),
    .B(Count[1]),
    .X(_16_)
  );
  sky130_fd_sc_hd__nand2_2 _29_ (
    .A(Count[0]),
    .B(Count[1]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nand2_2 _30_ (
    .A(_16_),
    .B(_17_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__inv_2 _31_ (
    .A(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__or2_2 _32_ (
    .A(Count[2]),
    .B(_16_),
    .X(_18_)
  );
  sky130_fd_sc_hd__a21bo_2 _33_ (
    .A1(Count[2]),
    .A2(_16_),
    .B1_N(_18_),
    .X(_08_)
  );
  sky130_fd_sc_hd__inv_2 _34_ (
    .A(Count[2]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__inv_2 _35_ (
    .A(_17_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__o22a_2 _36_ (
    .A1(_19_),
    .A2(_17_),
    .B1(Count[2]),
    .B2(_20_),
    .X(_09_)
  );
  sky130_fd_sc_hd__inv_2 _37_ (
    .A(Count[3]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _38_ (
    .A1_N(_21_),
    .A2_N(_18_),
    .B1(_21_),
    .B2(_18_),
    .X(_10_)
  );
  sky130_fd_sc_hd__o21a_2 _39_ (
    .A1(_19_),
    .A2(_17_),
    .B1(Count[3]),
    .X(_22_)
  );
  sky130_fd_sc_hd__a31o_2 _40_ (
    .A1(Count[2]),
    .A2(_20_),
    .A3(_21_),
    .B1(_22_),
    .X(_11_)
  );
  sky130_fd_sc_hd__buf_1 _41_ (
    .A(_14_),
    .X(_15_)
  );
  sky130_fd_sc_hd__mux2_1 _42_ (
    .A0(_04_),
    .A1(_05_),
    .S(UpOrDown),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _43_ (
    .A0(_06_),
    .A1(_07_),
    .S(UpOrDown),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _44_ (
    .A0(_08_),
    .A1(_09_),
    .S(UpOrDown),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _45_ (
    .A0(_10_),
    .A1(_11_),
    .S(UpOrDown),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfrtp_2 _46_ (
    .CLK(Clk),
    .D(_00_),
    .Q(Count[0]),
    .RESET_B(_12_)
  );
  sky130_fd_sc_hd__dfrtp_2 _47_ (
    .CLK(Clk),
    .D(_01_),
    .Q(Count[1]),
    .RESET_B(_13_)
  );
  sky130_fd_sc_hd__dfrtp_2 _48_ (
    .CLK(Clk),
    .D(_02_),
    .Q(Count[2]),
    .RESET_B(_14_)
  );
  sky130_fd_sc_hd__dfrtp_2 _49_ (
    .CLK(Clk),
    .D(_03_),
    .Q(Count[3]),
    .RESET_B(_15_)
  );
endmodule
